nodeLinker: pnp

packageExtensions:
    "@softarc/native-federation@*":
        dependencies:
            "tslib": "*"
    "@softarc/native-federation-esbuild@*":
        dependencies:
            "tslib": "*"
